services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    # .env needs to include MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD
    env_file: ".env"

volumes:
  mongodb:
    external: true
